<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>annotations</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>JyDraft</AssemblyName>
    <RootNamespace>JyDraft</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.0" />
    <PackageReference Include="MediaInfo.Wrapper.Core" Version="21.9.3" />
  </ItemGroup>
</Project>
